--SELECT * FROM orcamento_contabil.CONTA_CONTABIL cc FOR UPDATE

SELECT st.DS_SETOR, cc.ORDEM, cc.CD_CONTA_CONTABIL, cc.CD_CONTA_MV, pc.DS_CONTA, 
CASE 
  WHEN gpo.DS_GRUPO_ORCADO IS NULL THEN '-'
  ELSE gpo.DS_GRUPO_ORCADO
END AS DS_GRUPO_ORCADO, 
CASE
  WHEN gpo.VL_ORCADO IS NOT NULL THEN gpo.VL_ORCADO
  ELSE cc.VL_ORCADO
END VL_ORCADO,
CASE
  WHEN rm.VL_REALIZADO IS NOT NULL THEN rm.VL_REALIZADO
  ELSE 100 --TRAZER RESULTADO DO MV
END AS VL_REALIZADO 
FROM orcamento_contabil.CONTA_CONTABIL cc
INNER JOIN orcamento_contabil.SETOR st
  ON st.CD_SETOR = cc.CD_SETOR
LEFT JOIN orcamento_contabil.GRUPO_ORCADO gpo
  ON gpo.CD_GRUPO_ORCADO = cc.CD_GRUPO_ORCADO
LEFT JOIN orcamento_contabil.REALIZADO_MANUAL rm
  ON rm.CD_CONTA_CONTABIL = cc.CD_CONTA_CONTABIL
  AND rm.PERIODO = cc.PERIODO
INNER JOIN dbamv.PLANO_CONTAS pc
  ON pc.CD_REDUZIDO = cc.CD_CONTA_MV
WHERE cc.PERIODO = '05/2022'
ORDER BY st.DS_SETOR ASC, cc.ORDEM ASC, cc.CD_CONTA_MV ASC                                                
