SELECT TO_CHAR(DT_LCTO,'MM/YYYY') AS DT_LCTO_MES_ANO,
CD_REDUZIDO, CD_CONTABIL,
CASE
  WHEN SUBSTR(CD_CONTABIL,0,1) = 3 THEN 'RECEITA'
  WHEN SUBSTR(CD_CONTABIL,0,1) = 4 THEN 'DESPESA'
  ELSE '-'
END CLASSIFICACAO_CONTABIL,
DS_CONTA, SUM(SALDO_ATUAL) * -1 AS REALIZADO

FROM (
      SELECT TRUNC(lc.DT_LCTO) AS DT_LCTO, lc.CD_LOTE, lc.CD_LCTO_CONTABIL, lc.CD_LCTO_MOVIMENTO,
      lc.CD_MULTI_EMPRESA AS CD_MULTI_EMP_LANCAMENTO, pe.CD_REDUZIDO,
      lc.CD_AUXILIAR_DEB AS CD_CONTA_AUXILIAR, pe.CD_CONTABIL,pe.DS_CONTA, SUM(lc.VL_LANCADO) AS VL_DEBITO,
      SUM(0) VL_CREDITO, (0  + SUM(lc.VL_LANCADO) * DECODE(0 , 'D', 1, -1)) AS SALDO_ATUAL, lc.DS_COMPLEMENTO,
      hp.DS_HISTORICO_PADRAO, NULL AS DS_PROCESSO, NULL AS ESTRUTURAL_PROCESSO

      FROM dbamv.LCTO_CONTABIL lc

      INNER JOIN dbamv.PLANO_ESTR pe
        ON pe.CD_PLANO = 0001

      INNER JOIN dbamv.PLANO_CONTABIL depara
        ON depara.CD_REDUZIDO = lc.CD_REDUZIDO_DEBITO
        AND depara.CD_PLANO_ESTR = pe.CD_PLANO_ESTR

      LEFT JOIN dbamv.LOTE
        ON lc.CD_LOTE = LOTE.CD_LOTE

      LEFT JOIN dbamv.HISTORICO_PADRAO hp
        ON lc.CD_HISTORICO_PADRAO = hp.CD_HISTORICO_PADRAO

      WHERE lc.CD_REDUZIDO_DEBITO IS NOT NULL
      AND lc.CD_MULTI_EMPRESA IN (1)
      AND TRUNC(LC.DT_LCTO) >= TO_DATE('01/01/2022', 'DD/MM/YYYY')
                           
      GROUP BY TRUNC(lc.DT_LCTO), lc.CD_LOTE, lc.CD_LCTO_CONTABIL, lc.CD_LCTO_MOVIMENTO, lc.CD_MULTI_EMPRESA,
      pe.CD_REDUZIDO, lc.CD_AUXILIAR_DEB, pe.CD_CONTABIL, pe.DS_CONTA, lc.DS_COMPLEMENTO, hp.DS_HISTORICO_PADRAO

      UNION ALL

      SELECT TRUNC(lc.DT_LCTO), lc.CD_LOTE, lc.CD_LCTO_CONTABIL, lc.CD_LCTO_MOVIMENTO, lc.CD_MULTI_EMPRESA,
      pe.CD_REDUZIDO, lc.CD_AUXILIAR_CRD, pe.CD_CONTABIL, pe.DS_CONTA, SUM(0) AS VL_DEBITO,
      SUM(lc.VL_LANCADO) AS VL_CREDITO, (0  + SUM(lc.VL_LANCADO) * DECODE(0 , 'D', -1, 1)) AS SALDO_ATUAL,
      lc.DS_COMPLEMENTO, hp.DS_HISTORICO_PADRAO, NULL AS DS_PROCESSO, NULL AS ESTRUTURAL_PROCESSO

      FROM dbamv.LCTO_CONTABIL lc

      INNER JOIN dbamv.PLANO_ESTR pe
        ON pe.CD_PLANO = 0001

      INNER JOIN dbamv.PLANO_CONTABIL depara
        ON depara.CD_REDUZIDO = lc.CD_REDUZIDO_CREDITO
        AND depara.CD_PLANO_ESTR = pe.CD_PLANO_ESTR

      LEFT JOIN dbamv.LOTE
        ON lc.CD_LOTE = LOTE.CD_LOTE

      LEFT JOIN dbamv.HISTORICO_PADRAO hp
        ON lc.CD_HISTORICO_PADRAO = hp.CD_HISTORICO_PADRAO

      WHERE lc.CD_REDUZIDO_CREDITO IS NOT NULL
      AND lc.CD_MULTI_EMPRESA IN (1)
      AND TRUNC(LC.DT_LCTO) >= TO_DATE('01/01/2022', 'DD/MM/YYYY')
                           

      GROUP BY TRUNC(lc.DT_LCTO), lc.CD_LOTE, lc.CD_LCTO_CONTABIL, lc.CD_LCTO_MOVIMENTO, lc.CD_MULTI_EMPRESA,
      pe.CD_REDUZIDO, lc.CD_AUXILIAR_CRD, pe.CD_CONTABIL, pe.DS_CONTA, lc.DS_COMPLEMENTO, hp.DS_HISTORICO_PADRAO

      UNION ALL

      SELECT NULL, NULL, NULL, NULL, NULL, pe.CD_REDUZIDO , NULL, pe.CD_CONTABIL, pe.DS_CONTA, NULL, NULL,
      NULL, NULL, NULL, NULL AS DS_PROCESSO, NULL AS ESTRUTURAL_PROCESSO

      FROM dbamv.PLANO_ESTR pe

      WHERE  pe.CD_PLANO = 0001
      AND NOT EXISTS (
                      SELECT 'X'

                      FROM dbamv.LCTO_CONTABIL lc
                      ,dbamv.PLANO_CONTABIL depara

                      WHERE depara.CD_REDUZIDO = lc.CD_REDUZIDO_DEBITO
                      AND depara.CD_PLANO_ESTR = pe.CD_PLANO_ESTR
                      AND lc.CD_REDUZIDO_DEBITO IS NOT NULL
                      AND lc.CD_MULTI_EMPRESA IN (1))
                      AND NOT EXISTS (
                                      SELECT 'X'

                                      FROM dbamv.LCTO_CONTABIL lc
                                      ,dbamv.PLANO_CONTABIL depara

                                      WHERE depara.CD_REDUZIDO = lc.CD_REDUZIDO_CREDITO
                                      AND depara.CD_PLANO_ESTR = pe.CD_PLANO_ESTR
                                      AND lc.CD_REDUZIDO_CREDITO IS NOT NULL
                                      AND lc.CD_MULTI_EMPRESA IN (1))

      UNION ALL

      SELECT TRUNC(lc.DT_LCTO), lc.CD_LOTE, MIN(lc.CD_LCTO_CONTABIL) AS CD_LCTO_CONTABIL,
      MIN(lc.CD_LCTO_MOVIMENTO) CD_LCTO_MOVIMENTO, lc.CD_MULTI_EMPRESA, pe.CD_REDUZIDO, lc.CD_AUXILIAR_DEB,
      pe.CD_CONTABIL, pe.DS_CONTA, SUM(lc.VL_LANCADO) AS VL_DEBITO, SUM(0) VL_CREDITO,
      (0 + SUM(lc.VL_LANCADO) * DECODE(0 , 'D', 1, -1)) SALDO_ATUAL, 'DEPOSITO AGRUPADO' AS DS_COMPLEMENTO,
      hp.DS_HISTORICO_PADRAO, NULL AS DS_PROCESSO, NULL AS ESTRUTURAL_PROCESSO

      FROM dbamv.LCTO_CONTABIL lc

      INNER JOIN dbamv.PLANO_ESTR pe
        ON pe.CD_PLANO = 0001

      INNER JOIN dbamv.PLANO_CONTABIL depara
        ON depara.CD_REDUZIDO = lc.CD_REDUZIDO_debito
        AND depara.CD_PLANO_ESTR = pe.CD_PLANO_ESTR

      LEFT JOIN dbamv.LOTE
        ON lc.CD_LOTE = LOTE.CD_LOTE

      LEFT JOIN dbamv.HISTORICO_PADRAO hp
        ON lc.CD_HISTORICO_PADRAO = hp.CD_HISTORICO_PADRAO

      WHERE lc.CD_REDUZIDO_DEBITO IS NOT NULL
      AND lc.CD_MULTI_EMPRESA IN (1)
      AND TRUNC(LC.DT_LCTO) >= TO_DATE('01/01/2022', 'DD/MM/YYYY')
                            
      AND lc.CD_LANC_AGRUP IS NOT NULL

      GROUP BY TRUNC(lc.DT_LCTO), lc.CD_LOTE, lc.CD_MULTI_EMPRESA, pe.CD_REDUZIDO, lc.CD_AUXILIAR_DEB,
      pe.CD_CONTABIL, pe.DS_CONTA, hp.DS_HISTORICO_PADRAO, lc.CD_LANC_AGRUP, lc.SN_TRANSITORIA

      UNION ALL

      SELECT TRUNC(lc.DT_LCTO) DT_LCTO, lc.CD_LOTE, MIN(lc.CD_LCTO_CONTABIL) AS CD_LCTO_CONTABIL,
      MIN(lc.CD_LCTO_MOVIMENTO) AS CD_LCTO_MOVIMENTO, lc.CD_MULTI_EMPRESA, pe.CD_REDUZIDO,
      lc.CD_AUXILIAR_CRD, pe.CD_CONTABIL, pe.DS_CONTA, SUM(0) VL_DEBITO, SUM(lc.VL_LANCADO) AS VL_CREDITO,
      (0  + SUM(lc.VL_LANCADO) * DECODE(0 , 'D', -1, 1)) AS SALDO_ATUAL, 'DEPOSITO AGRUPADO' AS DS_COMPLEMENTO,
      hp.DS_HISTORICO_PADRAO, NULL AS DS_PROCESSO, NULL AS ESTRUTURAL_PROCESSO

      FROM dbamv.LCTO_CONTABIL lc

      INNER JOIN dbamv.PLANO_ESTR pe
        ON pe.CD_PLANO = 0001

      INNER JOIN dbamv.PLANO_CONTABIL depara
        ON depara.CD_REDUZIDO = lc.CD_REDUZIDO_CREDITO
        AND depara.CD_PLANO_ESTR = pe.CD_PLANO_ESTR

      LEFT JOIN dbamv.LOTE
        ON lc.CD_LOTE = LOTE.CD_LOTE

      LEFT JOIN dbamv.HISTORICO_PADRAO hp
        ON lc.CD_HISTORICO_PADRAO = hp.CD_HISTORICO_PADRAO

      WHERE lc.CD_REDUZIDO_CREDITO IS NOT NULL
      AND lc.CD_MULTI_EMPRESA IN (1)
      AND TRUNC(LC.DT_LCTO) >= TO_DATE('01/01/2022', 'DD/MM/YYYY')
                            
      AND lc.CD_LANC_AGRUP IS NOT NULL

      GROUP BY TRUNC(lc.DT_LCTO), lc.CD_LOTE, lc.CD_MULTI_EMPRESA, pe.CD_REDUZIDO, lc.CD_AUXILIAR_CRD,
      pe.CD_CONTABIL, pe.DS_CONTA, hp.DS_HISTORICO_PADRAO, lc.CD_LANC_AGRUP, lc.SN_TRANSITORIA

      ) res

WHERE DT_LCTO IS NOT NULL

GROUP BY TO_CHAR(DT_LCTO, 'MM/YYYY'), CD_REDUZIDO, CD_CONTABIL,
CASE
  WHEN SUBSTR(CD_CONTABIL,0,1) = 3 THEN 'RECEITA'
  WHEN SUBSTR(CD_CONTABIL,0,1) = 4 THEN 'DESPESA'
  ELSE '-'
END
,DS_CONTA
