--ATENCAO INSERIR AS REGRAS DO NULL E NOT NULL E VALIDAR NOVAMENTE
ALTER TABLE orcamento_contabil.CONTA_CONTABIL DROP CONSTRAINT FK_CD_SETOR_CONTA_CONTABIL;


--SETOR

DROP TABLE orcamento_contabil.SETOR;
CREATE TABLE orcamento_contabil.SETOR(

CD_SETOR            INT NOT NULL,
DS_SETOR            VARCHAR(100) NOT NULL,
NM_GESTOR           VARCHAR(20) NOT NULL,
SN_ATIVO            VARCHAR(1) NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT  TIMESTAMP,

CONSTRAINT check_sn_ativo CHECK (SN_ATIVO IN ('S', 'N')),
CONSTRAINT pk_cd_setor PRIMARY KEY (CD_SETOR)

);

DROP SEQUENCE seq_setor_cd_setor; 
CREATE SEQUENCE seq_setor_cd_setor 
START WITH 1    
INCREMENT BY   1
NOCACHE
NOCYCLE;

--GRUPO ORCADO

DROP TABLE orcamento_contabil.GRUPO_ORCADO;
CREATE TABLE orcamento_contabil.GRUPO_ORCADO(

CD_GRUPO_ORCADO     INT NOT NULL,
DS_GRUPO_ORCADO     VARCHAR(100) NOT NULL,
PERIODO             VARCHAR(7) NOT NULL,
VL_ORCADO           FLOAT NOT NULL,       
SN_ATIVO            VARCHAR(1) NOT NULL,   
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT  TIMESTAMP

--NAO HABILITAR POIS AFETA NO DUPLICAR PERIODO
--CONSTRAINT pk_cd_grupo_orcado PRIMARY KEY (CD_GRUPO_ORCADO)

);

DROP SEQUENCE seq_grupo_cd_grupo_orcado; 
CREATE SEQUENCE seq_grupo_cd_grupo_orcado 
START WITH 1    
INCREMENT BY   1
NOCACHE
NOCYCLE;

--CONTA_CONTABIL

DROP TABLE orcamento_contabil.CONTA_CONTABIL;
CREATE TABLE orcamento_contabil.CONTA_CONTABIL(

CD_CONTA_CONTABIL   INT NOT NULL,
CD_CONTA_MV         VARCHAR(100) NOT NULL,
CD_SETOR            INT NOT NULL,
PERIODO             VARCHAR(20) NOT NULL, 
ORDEM               INT NOT NULL,
SN_GRUPO_ORCADO     VARCHAR(20) NOT NULL, 
CD_GRUPO_ORCADO     VARCHAR(20), 
VL_ORCADO           FLOAT,         
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT  TIMESTAMP,

CONSTRAINT pk_cd_conta_contabil PRIMARY KEY (CD_CONTA_CONTABIL),
CONSTRAINT fk_cd_setor_conta_contabil FOREIGN KEY (CD_SETOR) REFERENCES setor(CD_SETOR)

);

DROP SEQUENCE seq_conta_cd_conta_contabil;
CREATE SEQUENCE seq_conta_cd_conta_contabil
START WITH 1    
INCREMENT BY   1
NOCACHE
NOCYCLE;

--REALIZADO MANUAL

DROP TABLE orcamento_contabil.REALIZADO_MANUAL;
CREATE TABLE orcamento_contabil.REALIZADO_MANUAL(

CD_REALIZADO_MANUAL INT NOT NULL,
CD_CONTA_CONTABIL   INT NOT NULL,
PERIODO             VARCHAR(7) NOT NULL,
VL_REALIZADO        FLOAT NOT NULL,   
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT  TIMESTAMP,

CONSTRAINT pk_cd_realizado_manual PRIMARY KEY (CD_REALIZADO_MANUAL)

);

DROP SEQUENCE seq_realiz_cd_realizado_manual;
CREATE SEQUENCE seq_realiz_cd_realizado_manual
START WITH 1    
INCREMENT BY   1
NOCACHE
NOCYCLE;
