CREATE OR REPLACE VIEW orcamento_contabil.VW_RESULTADOS_CONSOLIDADOS AS 

SELECT cc.PERIODO, st.DS_SETOR, cc.ORDEM, cc.CD_CONTA_CONTABIL, cc.CD_CONTA_MV, 
pc.DS_CONTA, 
CASE 
  WHEN SUBSTR(pc.CD_CONTABIL,0,1) = 3 THEN 'RECEITA'
  WHEN SUBSTR(pc.CD_CONTABIL,0,1) = 4 THEN 'DESPESA'
  ELSE 'AJUSTAR'
END AS TP_CONTA,
CASE 
 WHEN gpo.DS_GRUPO_ORCADO IS NULL THEN '-'
 ELSE gpo.DS_GRUPO_ORCADO
END AS DS_GRUPO_ORCADO, 
CASE
 WHEN gpo.VL_ORCADO IS NOT NULL THEN 
 TRIM(TO_CHAR(gpo.VL_ORCADO, '999G999G999G999D99'))
 ELSE 
 TRIM(TO_CHAR(cc.VL_ORCADO, '999G999G999G999D99'))  
END VL_ORCADO,
CASE
  WHEN rm.VL_REALIZADO IS NOT NULL THEN
  TRIM(TO_CHAR(rm.VL_REALIZADO, '999G999G999G999D99'))
  WHEN pc.TP_CONTA = 'RECEITA' THEN
  TRIM(TO_CHAR(ccr.REALIZADO * -1 , '999G999G999G999D99'))  
  ELSE
  TRIM(TO_CHAR(ccr.REALIZADO, '999G999G999G999D99'))        
END AS VL_REALIZADO,     
CASE
  WHEN rm.VL_REALIZADO IS NOT NULL THEN
  'S'
  ELSE
  'N'      
END AS SN_MANUAL
FROM orcamento_contabil.CONTA_CONTABIL cc
INNER JOIN orcamento_contabil.SETOR st
 ON st.CD_SETOR = cc.CD_SETOR
LEFT JOIN orcamento_contabil.GRUPO_ORCADO gpo
 ON gpo.CD_GRUPO_ORCADO = cc.CD_GRUPO_ORCADO
LEFT JOIN orcamento_contabil.REALIZADO_MANUAL rm
 ON rm.CD_CONTA_CONTABIL = cc.CD_CONTA_CONTABIL
 AND rm.PERIODO = cc.PERIODO
LEFT JOIN dbamv.MVW_CONTA_CONTABIL_REALIZADO ccr
 ON ccr.CD_REDUZIDO = cc.CD_CONTA_MV
 AND ccr.DT_LCTO_MES_ANO = cc.PERIODO
INNER JOIN dbamv.PLANO_CONTAS pc
 ON pc.CD_REDUZIDO = cc.CD_CONTA_MV
ORDER BY st.DS_SETOR ASC, cc.ORDEM ASC, cc.CD_CONTA_MV ASC
