CREATE OR REPLACE VIEW VW_RESULTADO_DESVIO AS
SELECT SUBSTR(vrc.PERIODO,4,4) AS ANO, SUBSTR(vrc.PERIODO,0,2) AS MES,
CASE
  WHEN SUBSTR(vrc.PERIODO,0,2) = 1 THEN 'JAN'
  WHEN SUBSTR(vrc.PERIODO,0,2) = 2 THEN 'FEV'
  WHEN SUBSTR(vrc.PERIODO,0,2) = 3 THEN 'MAR'
  WHEN SUBSTR(vrc.PERIODO,0,2) = 4 THEN 'ABR'
  WHEN SUBSTR(vrc.PERIODO,0,2) = 5 THEN 'MAI'
  WHEN SUBSTR(vrc.PERIODO,0,2) = 6 THEN 'JUN'
  WHEN SUBSTR(vrc.PERIODO,0,2) = 7 THEN 'JUL'
  WHEN SUBSTR(vrc.PERIODO,0,2) = 8 THEN 'AGO'
  WHEN SUBSTR(vrc.PERIODO,0,2) = 9 THEN 'SET'
  WHEN SUBSTR(vrc.PERIODO,0,2) = 10 THEN 'OUT'
  WHEN SUBSTR(vrc.PERIODO,0,2) = 11 THEN 'NOV'
  WHEN SUBSTR(vrc.PERIODO,0,2) = 12 THEN 'DEZ'
END AS MES_ABV,
vrc.CLASSIFICACAO_CONTABIL,
NVL(SUM(REPLACE(vrc.VL_ORCADO,'.','')),0) AS VL_ORCADO,
NVL(SUM(REPLACE(vrc.VL_REALIZADO,'.','')),0) AS VL_REALIZADO,
CASE
  WHEN NVL(SUM(REPLACE(vrc.VL_ORCADO,'.','')),0) = 0 THEN 0
  ELSE ROUND(((NVL(SUM(REPLACE(vrc.VL_REALIZADO,'.','')),0) - NVL(SUM(REPLACE(vrc.VL_ORCADO,'.','')),0)) / NVL(SUM(REPLACE(vrc.VL_ORCADO,'.','')),0))*100,2) 
END AS PORC_DESVIO
--SELECT *
FROM orcamento_contabil.VW_RESULTADOS_CONSOLIDADOS vrc
WHERE vrc.CLASSIFICACAO_CONTABIL IN ('RECEITA','DESPESA')
GROUP BY SUBSTR(vrc.PERIODO,4,4), SUBSTR(vrc.PERIODO,0,2),
vrc.CLASSIFICACAO_CONTABIL
;
